# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43hatService.proto\"\x1f\n\tClientTxt\x12\x12\n\nclient_txt\x18\x01 \x01(\t\"\x1f\n\tServerTxt\x12\x12\n\nserver_txt\x18\x01 \x01(\t23\n\x0b\x43hatService\x12$\n\x04\x63hat\x12\n.ClientTxt\x1a\n.ServerTxt\"\x00(\x01\x30\x01\x62\x06proto3')



_CLIENTTXT = DESCRIPTOR.message_types_by_name['ClientTxt']
_SERVERTXT = DESCRIPTOR.message_types_by_name['ServerTxt']
ClientTxt = _reflection.GeneratedProtocolMessageType('ClientTxt', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTTXT,
  '__module__' : 'ChatService_pb2'
  # @@protoc_insertion_point(class_scope:ClientTxt)
  })
_sym_db.RegisterMessage(ClientTxt)

ServerTxt = _reflection.GeneratedProtocolMessageType('ServerTxt', (_message.Message,), {
  'DESCRIPTOR' : _SERVERTXT,
  '__module__' : 'ChatService_pb2'
  # @@protoc_insertion_point(class_scope:ServerTxt)
  })
_sym_db.RegisterMessage(ServerTxt)

_CHATSERVICE = DESCRIPTOR.services_by_name['ChatService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTTXT._serialized_start=21
  _CLIENTTXT._serialized_end=52
  _SERVERTXT._serialized_start=54
  _SERVERTXT._serialized_end=85
  _CHATSERVICE._serialized_start=87
  _CHATSERVICE._serialized_end=138
# @@protoc_insertion_point(module_scope)
